<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('desain_industri')->insert([
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2024-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2025-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2026-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
            [
                'user_id' => 3,
                'nama_lengkap' => "Suhendi",
                'alamat' => "Jatibarang Blok Gudang",
                'no_telepon' => "081214627146",
                'tanggal_lahir' => "1985-06-25",
                'ktp_inventor' => "Suhendi.pdf",
                'email' => "suhendi@gmail.com",
                'kewarganegaraan' => "Indonesia",
                'kode_pos' => "45273",
                'institusi' => "",
                'jenis_di' => "",
                'judul_di' => "Logo Asal Wawuh",
                'uraian_di' => "asal wawuh ayo ngaji",
                'gambar_di' => "Suhendi.pdf",
                'surat_kepemilikan' => "2024-07-01",
                'surat_pengalihan' => "suhendi.pdf",
                'tanggal_permohonan' => "2027-07-01",
                'status' => "Diberi",
                'sertifikat_desain' => "Suhendi.pdf",
            ],
        ]);
    }
}
