<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HCSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('hak_cipta')->insert([
            [
            'user_id' => 3,
            'nama_lengkap' => "Suhendi",
            'alamat' => "Jatibarang Blok Gudang",
            'no_telepon' => "081214627146",
            'tanggal_lahir' => "1985-06-25",
            'ktp_inventor' => "Suhendi.pdf",
            'email' => "Suhendi@gmail.com",
            'kewarganegaraan' => "Indonesia",
            'kode_pos' => "45273",
            'institusi' => "",
            'jurusan' => "",
            'prodi' => "",
            'jenis_ciptaan' => "Karya Tulis",
            'judul_ciptaan' => "Nadozm Hizbi.pdf",
            'uraian_singkat' => "Deres",
            'dokumen_invensi' => "Suhendi.pdf",
            'surat_pengalihan' => "Suhendi.pdf",
            'surat_pernyataan' => "Suhendi.pdf",
            'tanggal_permohonan' => "2027-07-01",
            'status' => "Tercatat",
            'sertifikat_hakcipta' => "Suhendi.pdf",
            ],
            [
            'user_id' => 3,
            'nama_lengkap' => "Suhendi",
            'alamat' => "Jatibarang Blok Gudang",
            'no_telepon' => "081214627146",
            'tanggal_lahir' => "1985-06-25",
            'ktp_inventor' => "Suhendi.pdf",
            'email' => "Suhendi@gmail.com",
            'kewarganegaraan' => "Indonesia",
            'kode_pos' => "45273",
            'institusi' => "",
            'jurusan' => "",
            'prodi' => "",
            'jenis_ciptaan' => "Karya Tulis",
            'judul_ciptaan' => "Nadozm Hizbi.pdf",
            'uraian_singkat' => "Deres",
            'dokumen_invensi' => "Suhendi.pdf",
            'surat_pengalihan' => "Suhendi.pdf",
            'surat_pernyataan' => "Suhendi.pdf",
            'tanggal_permohonan' => "2027-07-01",
            'status' => "Tercatat",
            'sertifikat_hakcipta' => "Suhendi.pdf",
            ],
            [
            'user_id' => 3,
            'nama_lengkap' => "Suhendi",
            'alamat' => "Jatibarang Blok Gudang",
            'no_telepon' => "081214627146",
            'tanggal_lahir' => "1985-06-25",
            'ktp_inventor' => "Suhendi.pdf",
            'email' => "Suhendi@gmail.com",
            'kewarganegaraan' => "Indonesia",
            'kode_pos' => "45273",
            'institusi' => "",
            'jurusan' => "",
            'prodi' => "",
            'jenis_ciptaan' => "Karya Tulis",
            'judul_ciptaan' => "Nadozm Hizbi.pdf",
            'uraian_singkat' => "Deres",
            'dokumen_invensi' => "Suhendi.pdf",
            'surat_pengalihan' => "Suhendi.pdf",
            'surat_pernyataan' => "Suhendi.pdf",
            'tanggal_permohonan' => "2027-07-01",
            'status' => "Tercatat",
            'sertifikat_hakcipta' => "Suhendi.pdf",
            ],
            [
            'user_id' => 3,
            'nama_lengkap' => "Suhendi",
            'alamat' => "Jatibarang Blok Gudang",
            'no_telepon' => "081214627146",
            'tanggal_lahir' => "1985-06-25",
            'ktp_inventor' => "Suhendi.pdf",
            'email' => "Suhendi@gmail.com",
            'kewarganegaraan' => "Indonesia",
            'kode_pos' => "45273",
            'institusi' => "",
            'jurusan' => "",
            'prodi' => "",
            'jenis_ciptaan' => "Karya Tulis",
            'judul_ciptaan' => "Nadozm Hizbi.pdf",
            'uraian_singkat' => "Deres",
            'dokumen_invensi' => "Suhendi.pdf",
            'surat_pengalihan' => "Suhendi.pdf",
            'surat_pernyataan' => "Suhendi.pdf",
            'tanggal_permohonan' => "2027-07-01",
            'status' => "Tercatat",
            'sertifikat_hakcipta' => "Suhendi.pdf",
            ],
            [
            'user_id' => 3,
            'nama_lengkap' => "Suhendi",
            'alamat' => "Jatibarang Blok Gudang",
            'no_telepon' => "081214627146",
            'tanggal_lahir' => "1985-06-25",
            'ktp_inventor' => "Suhendi.pdf",
            'email' => "Suhendi@gmail.com",
            'kewarganegaraan' => "Indonesia",
            'kode_pos' => "45273",
            'institusi' => "",
            'jurusan' => "",
            'prodi' => "",
            'jenis_ciptaan' => "Karya Tulis",
            'judul_ciptaan' => "Nadozm Hizbi.pdf",
            'uraian_singkat' => "Deres",
            'dokumen_invensi' => "Suhendi.pdf",
            'surat_pengalihan' => "Suhendi.pdf",
            'surat_pernyataan' => "Suhendi.pdf",
            'tanggal_permohonan' => "2027-07-01",
            'status' => "Tercatat",
            'sertifikat_hakcipta' => "Suhendi.pdf",
            ],
            [
            'user_id' => 3,
            'nama_lengkap' => "Suhendi",
            'alamat' => "Jatibarang Blok Gudang",
            'no_telepon' => "081214627146",
            'tanggal_lahir' => "1985-06-25",
            'ktp_inventor' => "Suhendi.pdf",
            'email' => "Suhendi@gmail.com",
            'kewarganegaraan' => "Indonesia",
            'kode_pos' => "45273",
            'institusi' => "",
            'jurusan' => "",
            'prodi' => "",
            'jenis_ciptaan' => "Karya Tulis",
            'judul_ciptaan' => "Nadozm Hizbi.pdf",
            'uraian_singkat' => "Deres",
            'dokumen_invensi' => "Suhendi.pdf",
            'surat_pengalihan' => "Suhendi.pdf",
            'surat_pernyataan' => "Suhendi.pdf",
            'tanggal_permohonan' => "2027-07-01",
            'status' => "Tercatat",
            'sertifikat_hakcipta' => "Suhendi.pdf",
            ],
        
        ]);
    }
}
